EconomicUI/Models/ApiHelper.cs
using System.Threading.Tasks;
using RestSharp;

namespace EconomicUI.Models
{
  class ApiHelper
  {
    //Getting all the states
    public static async Task<string> GetAll()
    {
      RestClient client = new RestClient("http://localhost:5000/api");
      RestRequest request = new RestRequest($"states", Method.GET);
      var response = await client.ExecuteTaskAsync(request);
      return response.Content;
    }
    //Searching for a specific state
    public static async Task<string> GetSearchResults(string name)
    {
      RestClient client = new RestClient("http://localhost:5000/api");
      RestRequest request = new RestRequest($"states/states/?name={name}", Method.GET);
      var response = await client.ExecuteTaskAsync(request);
      return response.Content;
    }

    //Details for state
    public static async Task<string> Get(int id)
    {
      RestClient client = new RestClient("http://localhost:5000/api");
      RestRequest request = new RestRequest($"states/{id}", Method.GET);
      var response = await client.ExecuteTaskAsync(request);
      return response.Content;
    }

    //Post a new state
    public static async Task Post(string newState)
    {
      RestClient client = new RestClient("http://localhost:5000/api");
      RestRequest request = new RestRequest($"states", Method.POST);
      request.AddHeader("Content-Type", "application/json");
      request.AddJsonBody(newState);
      var response = await client.ExecuteTaskAsync(request);
    }
    
    //Put for the state
    public static async Task Put(int id, string newState)
    {
      RestClient client = new RestClient("http://localhost:5000/api");
      RestRequest request = new RestRequest($"states/{id}", Method.PUT);
      request.AddHeader("Content-Type", "application/json");
      request.AddJsonBody(newState);
      var response = await client.ExecuteTaskAsync(request);
    }

    // Delete for the state
    public static async Task Delete(int id)
    {
      RestClient client = new RestClient("http://localhost:5000/api");
      RestRequest request = new RestRequest($"states/{id}", Method.DELETE);
      request.AddHeader("Content-Type", "application/json");
      var response = await client.ExecuteTaskAsync(request);
    }
  }
}

EconomicUI/Models/ErrorViewModel.cs
using System;

namespace EconomicUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EconomicUI/Models/State.cs
using System.Collections.Generic;
using System;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Threading.Tasks;

namespace EconomicUI.Models
{
  public class State
  {
    public int StateId { get; set; }
    public string Name { get; set; }
    public int GDP { get; set; }
    public string MainExport { get; set; }
    public string MainImport { get; set; }
    public State()
    {

    }
    public State(string name)
    {
      Name = name;
    }
    public static List<State> GetStates()
    {
      var apiCallTask = ApiHelper.GetAll();
      var result = apiCallTask.Result;

      JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
      List<State> stateList = JsonConvert.DeserializeObject<List<State>>(jsonResponse.ToString());

      return stateList;
    }
    public static List<State> SearchStates(string name)
    {
      var apiCallTask = ApiHelper.GetSearchResults(name);
      var result = apiCallTask.Result;

      JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
      List<State> state = JsonConvert.DeserializeObject<List<State>>(jsonResponse.ToString());

      return state;
    }

    public static State GetDetails(int id)
    {
      var apiCallTask = ApiHelper.Get(id);
      var result = apiCallTask.Result;

      JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
      State state = JsonConvert.DeserializeObject<State>(jsonResponse.ToString());
      
      return state;
    }

    public static void Post(State state)
    {
      string jsonState = JsonConvert.SerializeObject(state);
      var apiCallTask = ApiHelper.Post(jsonState);
    }

    public static void Put(State state)
    {
      string jsonState = JsonConvert.SerializeObject(state);
      var apiCallTask = ApiHelper.Put(state.StateId, jsonState);
    }

    public static void Delete(int id)
    {
      var apiCallTask = ApiHelper.Delete(id);
    }
  }
}

EconomicUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EconomicUI.Models;

namespace EconomicUI.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet("/")]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EconomicUI/Controllers/StatesController.cs
using Microsoft.AspNetCore.Mvc;
using EconomicUI.Models;

namespace EconomicUI.Controllers
{
  public class StatesController : Controller
  {
    [HttpGet]
    public IActionResult Index()
    {
      var allStates = State.GetStates();
      return View(allStates);
    }

    // [HttpGet("States")]
    public IActionResult Search(string name)
    {
        var searchedStates = State.SearchStates(name);
        return View(searchedStates);
    }

    // [HttpGet("Details")]
    public IActionResult Details(int id)
    {
      var state = State.GetDetails(id);
      return View(state);
    }

    public IActionResult Edit(int id)
    {
      var state = State.GetDetails(id); 
      return View(state);
    }

    [HttpPost]
    public IActionResult Details(int id, State state)
    {
      state.StateId = id;
      State.Put(state);
      return RedirectToAction("Details", id);
    }

    public IActionResult Delete(int id)
    {
      State.Delete(id);
      return RedirectToAction("Index");
    }
  }
}

EconomicUI/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}

<div class="text-center">
    <h1 class="display-4">Economic Mapping DataBase</h1>
    <input type="button" value="See all States" onclick="location.href='@Url.Action("Index", "States")';" class="btn btn-primary" /><br><br>
    @using (Html.BeginForm("Search", "States", FormMethod.Get))
    {
        <div class="form-group">
            <p>Search States: @Html.TextBox("search", null , new {@class="form-control"})</p>
        </div>
        <input type="button" value="Search States" onclick="location.href='@Url.Action("Search", "States")';" class="btn btn-primary" />
    }
</div>

EconomicUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - States Economic Map</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
                asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
                crossorigin="anonymous"
                integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">States Economic Map</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="States">States</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
            &copy; 2020 - EconomicMappingUI.solution - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

EconomicUI/Views/States/Create.cshtml
@{
  Layout = "_Layout";
}

@model EconomicUI.Models.State

<h4>Add a new State</h4>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    @Html.LabelFor(model => model.GDP)
    @Html.TextBoxFor(model => model.GDP)
    @Html.LabelFor(model => model.MainImport)
    @Html.TextBoxFor(model => model.MainImport)
    @Html.LabelFor(model => model.MainExport)
    @Html.TextBoxFor(model => model.MainExport)
    

    <input type="submit" value="Add new State" class="btn btn-default" />
}
<input type="button" value="Back to list" onclick="location.href='@Url.Action("Index", "States")';" class="btn btn-primary" />
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" />

EconomicUI/Views/States/Details.cshtml
@{
  Layout = "_Layout";
}

@model EconomicUI.Models.State

<h1>State Details</h1>

<ul>
  <li>@Html.DisplayNameFor(model => model.StateId): @Html.DisplayFor(model => model.StateId)</li>
  <li>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</li>
  <li>@Html.DisplayNameFor(model => model.GDP): @Html.DisplayFor(model => model.GDP)</li>
  <li>@Html.DisplayNameFor(model => model.MainExport): @Html.DisplayFor(model => model.MainExport)</li>
  <li>@Html.DisplayNameFor(model => model.MainImport): @Html.DisplayFor(model => model.MainImport)</li>
</ul>


<input type="button" value="Delete State" onclick="location.href='@Url.Action("Delete", "States", new { id = Model.StateId })';" class="btn btn-warning" />
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" />
<input type="button" value="Edit State" onclick="location.href='@Url.Action("Edit", "States", new { id = Model.StateId })';" class="btn btn-primary" />
<input type="button" value="Back to list" onclick="location.href='@Url.Action("Index", "States")';" class="btn btn-primary" />

EconomicUI/Views/States/Edit.cshtml
@{
  Layout = "_Layout";
}

@model EconomicUI.Models.State

<h2>Edit</h2>

<h4>Edit this State: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StateId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  @Html.LabelFor(model => model.GDP)
  @Html.TextBoxFor(model => model.GDP)

  @Html.LabelFor(model => model.MainImport)
  @Html.EditorFor(model => model.MainImport)

  @Html.LabelFor(model => model.MainExport)
  @Html.EditorFor(model => model.MainExport)

  <input type="submit" value="Save" />
}
<input type="button" value="Back to list" onclick="location.href='@Url.Action("Index", "States")';" class="btn btn-primary" />
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" />

EconomicUI/Views/States/Index.cshtml
@{
    Layout = "_Layout";
}

@using EconomicUI.Models

<h1 style='text-align: center'>All States</h1>

<ol>
@foreach (State state in Model)
{
    <ul>
        <li>ID: @state.StateId</li>
        <li>Name: @state.Name</li>
        <li>GDP: @state.GDP</li>
        <li>Main Import: @state.MainImport</li>
        <li>Main Export: @state.MainExport</li>
    </ul>
    <a href="/States/Details/@(state.StateId)"><p>View Details</p></a>
    <br>
}
</ol>
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" />

EconomicUI/Views/States/Search.cshtml
@{
    Layout = "_Layout";
}
@using EconomicUI.Models

<h1>Search Results:</h1>

<ul>

    @foreach (var item in Model)
    {
        <li>ID: @item.StateId</li>
        <li>Name: @item.Name</li>
        <li>GDP: @item.GDP</li>
        <li>Main Import: @item.MainImport</li>
        <li>Main Export: @item.MainExport</li>
    }
</ul>

<input type="button" value="Back to list" onclick="location.href='@Url.Action("Index", "States")';" class="btn btn-primary" />
<input type="button" value="Return Home" onclick="location.href='@Url.Action("Index", "Home")';" class="btn btn-primary" />